# Generated by Django 3.1 on 2020-08-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200830_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registrationno',
            field=models.IntegerField(null=True),
        ),
    ]
